kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-template
  labels:
    name: ${NAME}-template
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}-allow-ingress
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the drupal container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
      replicas: 1
      test: false
      selector:
        name: ${NAME}
      template:
        metadata:
          labels:
            name: ${NAME}
            app: ${APP_NAME}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          volumes:
            - name: ${NAME}-data
              persistentVolumeClaim:
                claimName: ${NAME}-data
            - name: ${NAME}-php-ini
              configMap:
                name: ${DRUPAL_CONFIG_MAP_NAME}
                items:
                  - key: ${PHP_INI_FILE_NAME}
                    path: ${PHP_INI_FILE_NAME}
            - name: ${NAME}-settings-php
              configMap:
                name: ${DRUPAL_CONFIG_MAP_NAME}
                items:
                  - key: ${SITE_SETTINGS_FILE_NAME}
                    path: ${SITE_SETTINGS_FILE_NAME}
            - name: ${NAME}-htaccess
              configMap:
                name: ${DRUPAL_CONFIG_MAP_NAME}
                items:
                  - key: .htaccess
                    path: .htaccess
          containers:
            - image: ${SOURCE_IMAGE_NAME}
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 5
              name: ${NAME}
              env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: drupal-db
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: drupal-db
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: drupal-db
                - name: MYSQL_HOST
                  value: drupal-db
                - name: MYSQL_PORT
                  value: "3306"
                - name: SITE_SETTINGS_FILE_NAME
                  value: ${SITE_SETTINGS_FILE_NAME}
                - name: HTTP_AUTH_USER
                  valueFrom:
                    secretKeyRef:
                      key: user
                      name: ${NAME}-http-auth
                - name: HTTP_AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: ${NAME}-http-auth
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - name: ${NAME}-data
                  mountPath: ${DRUPAL_DATA_MOUNT_PATH}
                - name: ${NAME}-php-ini
                  mountPath: ${PHP_INI_MOUNT_PATH}${PHP_INI_FILE_NAME}
                  subPath: ${PHP_INI_FILE_NAME}
                - name: ${NAME}-settings-php
                  mountPath: /opt/drupal/web/sites/default/${SITE_SETTINGS_FILE_NAME}
                  subPath: ${SITE_SETTINGS_FILE_NAME}
                - name: ${NAME}-htaccess
                  mountPath: ${HTACCESS_MOUNT_PATH}/.htaccess
                  subPath: .htaccess
              lifecycle:
                postStart:
                  exec:
                    command:
                      - "/bin/sh"
                      - "-c"
                      - >
                        if [ ! -z "${HTTP_AUTH_USER}" ] && [ ! -z "${HTTP_AUTH_PASSWORD}" ]; then
                        htpasswd -b /opt/drupal/web/.htpasswd "${HTTP_AUTH_USER}" "${HTTP_AUTH_PASSWORD}";
                        fi

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-data
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      storageClassName: ${PERSISTENT_VOLUME_CLASS}
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${PERSISTENT_VOLUME_SIZE}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        haproxy.router.openshift.io/timeout: ${ROUTE_TIMEOUT}
    spec:
      host: ${APPLICATION_DOMAIN}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-admin
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      username: ${DRUPAL_ADMIN_USER}
      password: ${DRUPAL_ADMIN_PASSWORD}
    type: Opaque
  
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-http-auth
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      user: ${HTTP_AUTH_USER}
      password: ${HTTP_AUTH_PASSWORD}
    type: Opaque

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${NAME}
      type: ClusterIP
      sessionAffinity: None

parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: drupal
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: jag-lrb-web
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description:
      The namespace of the OpenShift project containing the imagestream
      for the application.
    value: 6b08a3
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: drupal
  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The name of the namespace being deployed to..
    required: true
    value: 6b08a3
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: drupal
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: drupal
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: prod
  - name: DRUPAL_ADMIN_USER
    displayName: Drupal Admin Username
    description: Admin Username for Drupal
    required: true
    value: admin
  - name: DRUPAL_ADMIN_PASSWORD
    displayName: Drupal Admin Password
    description: Password for the Drupal Admin user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: HTTP_AUTH_USER
    displayName: Basic Auth Username
    description: Username to be used for basic auth. If no user is specified, basic auth will not be enabled. 
    required: false
    value: 
  - name: HTTP_AUTH_PASSWORD
    displayName: Basic Auth Password
    description: Password to be used for basic auth. If no user is specified, basic auth will not be enabled.
    required: false
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: APPLICATION_DOMAIN
    displayName: APPLICATION_DOMAIN
    description:
      The public domain endpoint for Drupal. A value will be created by
      default if not specified.
    required: true
    value: ""
  - name: ROUTE_TIMEOUT
    displayName: Route Timeout
    description: The timeout for the application route.  When this timeout is exceeded the application's route will respond with a 504 Gateway Timeout error.
    required: true
    value: 120s
  - name: PHP_INI_FILE_NAME
    displayName: php.ini Config File Name
    description: The name of the configuration file to be used for php.ini.
    required: true
    value: php.ini
  - name: PHP_INI_MOUNT_PATH
    displayName: php.ini Mount Path
    description: The path to use to mount the php.ini file.
    required: true
    value: /usr/local/etc/php/
  - name: SITE_SETTINGS_FILE_NAME
    displayName: Site Settings File Name
    description: The name of the configuration file to be used for the default site.
    required: true
    value: settings.php
  - name: HTACCESS_MOUNT_PATH
    displayName: HTAccess Mount Path
    description: The path to use to mount the .htaccess config file.
    required: true
    value: /opt/drupal/web
  - name: DRUPAL_CONFIG_MAP_NAME
    displayName: Drupal Config Map Name
    description: The name of the configuration map.
    required: true
    value: drupal-settings
  - name: DRUPAL_DATA_MOUNT_PATH
    displayName: Drupal Data Mount Path
    description: The path to use to mount the volume where user files are persisted.
    required: true
    value: /opt/drupal/web/files
  - name: PERSISTENT_VOLUME_SIZE
    displayName: Persistent Volume Size
    description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
    required: true
    value: 1Gi
  - name: PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; netapp-file-standard, netapp-file-extended, netapp-block-standard, netapp-block-extended, netapp-file-backup
    required: false
    value: netapp-file-standard
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 250m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
